class ShaadiMatchDataModel {
  static final categoryitems = [
    ShaadiItem(
      id: "AP1234567",
      name: 'Monika Mishra',
      details:
          'It is a pleasure sharing a few words about my relative.\nShe has completed her B.Ed. Her optimistic personality is adored by one and all. She is looking for a boy with whom she can lead a happy.',
      dob: '12-Jun-1991',
      time: "11:30 AM",
      profileImg: ["https://i.pinimg.com/originals/09/ee/97/09ee9790e4a873be73302693a56a9bf6.jpg",'https://i.pinimg.com/736x/d5/a7/a6/d5a7a641eff0e09f95e0949e56621eb4.jpg'],
      isNew: true,
      mobile: '88441424151',
      countryCode: "+91",
      email: 'monika@gmail.com',
      fathersName: "Satish Agarwal",
      motherName: '',
      gender: 'Female',
      income: "7-10 LPA",
      accountType: "Normal",
      height: "5'2",
      ageAgo: '27 yrs',
      country: 'India',
      state: "Karnataka",
      city: "Bengaluru",
      category: "Gupta",
      subCategory: "Baniya",
      maritalStatus: "Never Married",
      religion: "Hindu",
      motherTongue: "Hindi",
      community: "Agarwal",
      dietPreferences: "Vegetarian",
      profession: "Currently not working",
      highestQualification: "B.Ed - Bachelor of Education",
      education: "Arts / Design",
      collegeName: "University of Kota",
      annualIncome: "Earns INR 20 Lakh to 30 Lakh annually",
      companyName: "Axis Bank",
      fatherOccupation: "Businessman",
      fatherJobStatus: "Retired",
      motherOccupation: "Housemaker",
      motherJobStatus: "",
      familyClass: "Middle class",
      familyValue: "Traditional Values",
      noOfBrother: "1",
      noOfBrotherMarried: "Married",
      noOfSister: "0",
      noOfSisterMarried: "Unmarried",
        manglik: true,
      createdBy: "Other",
    ),
    ShaadiItem(
      id: "AP1234567",
      name: 'Nandini Singhal',
      details:
          'It is a pleasure sharing a few words about my relative.\nShe has completed her B.Ed. Her optimistic personality is adored by one and all. She is looking for a boy with whom she can lead a happy.',
      dob: '12-Jun-1991',
      time: "11:30 AM",
      profileImg: ['https://i.pinimg.com/736x/d5/a7/a6/d5a7a641eff0e09f95e0949e56621eb4.jpg'],
      isNew: true,
      mobile: '88441424151',
      countryCode: "+91",
      email: 'monika@gmail.com',
      fathersName: "Satish Agarwal",
      motherName: '',
      gender: 'Female',
      income: "7-10 LPA",
      accountType: "Normal",
      height: "5'2",
      ageAgo: '25 yrs',
      country: 'India',
      state: "Himachal Pradesh",
      city: "Shimla",
      category: "Agarwal",
      subCategory: "Baniya",
      maritalStatus: "Never Married",
      religion: "Hindu",
      motherTongue: "Hindi",
      community: "Agarwal",
      dietPreferences: "vegetarian",
      profession: "Currently not working",
      highestQualification: "B.Ed - Bachelor of Education",
      education: "Arts / Design",
      collegeName: "University of Kota",
      annualIncome: "Doesn't wish to specify her income",
      companyName: "null",
      fatherOccupation: "Businessman",
      fatherJobStatus: "Retired",
      motherOccupation: "Housemaker",
      motherJobStatus: "",
      familyClass: "Middle class",
      familyValue: "Traditional Values",
      noOfBrother: "0",
      noOfBrotherMarried: "Married",
      noOfSister: "1",
      noOfSisterMarried: "Unmarried",
        manglik: false,
        createdBy: "Other",
    ),

    ShaadiItem(
      id: "AP1234567",
      name: 'Nandini Singhal',
      details:
      'It is a pleasure sharing a few words about my relative.\nShe has completed her B.Ed. Her optimistic personality is adored by one and all. She is looking for a boy with whom she can lead a happy.',
      dob: '12-Jun-1991',
      time: "11:30 AM",
      profileImg: ['https://funmauj.b-cdn.net/test/388799.jpg'],
      isNew: true,
      mobile: '88441424151',
      countryCode: "+91",
      email: 'monika@gmail.com',
      fathersName: "Satish Agarwal",
      motherName: '',
      gender: 'Female',
      income: "7-10 LPA",
      accountType: "Normal",
      height: "5'2",
      ageAgo: '25 yrs',
      country: 'India',
      state: "Himachal Pradesh",
      city: "Shimla",
      category: "Agarwal",
      subCategory: "Baniya",
      maritalStatus: "Never Married",
      religion: "Hindu",
      motherTongue: "Hindi",
      community: "Agarwal",
      dietPreferences: "vegetarian",
      profession: "Currently not working",
      highestQualification: "B.Ed - Bachelor of Education",
      education: "Arts / Design",
      collegeName: "University of Kota",
      annualIncome: "Doesn't wish to specify her income",
      companyName: "null",
      fatherOccupation: "Businessman",
      fatherJobStatus: "Retired",
      motherOccupation: "Housemaker",
      motherJobStatus: "",
      familyClass: "Middle class",
      familyValue: "Traditional Values",
      noOfBrother: "0",
      noOfBrotherMarried: "Married",
      noOfSister: "1",
      noOfSisterMarried: "Unmarried",
      manglik: false,
      createdBy: "Other",
    ),


    ShaadiItem(
      id: "AP1234567",
      name: 'Nandini Singhal',
      details:
      'It is a pleasure sharing a few words about my relative.\nShe has completed her B.Ed. Her optimistic personality is adored by one and all. She is looking for a boy with whom she can lead a happy.',
      dob: '12-Jun-1991',
      time: "11:30 AM",
      profileImg: ['https://funmauj.b-cdn.net/test/388799.jpg'],
      isNew: true,
      mobile: '88441424151',
      countryCode: "+91",
      email: 'monika@gmail.com',
      fathersName: "Satish Agarwal",
      motherName: '',
      gender: 'Female',
      income: "7-10 LPA",
      accountType: "Normal",
      height: "5'2",
      ageAgo: '25 yrs',
      country: 'India',
      state: "Himachal Pradesh",
      city: "Shimla",
      category: "Agarwal",
      subCategory: "Baniya",
      maritalStatus: "Never Married",
      religion: "Hindu",
      motherTongue: "Hindi",
      community: "Agarwal",
      dietPreferences: "vegetarian",
      profession: "Currently not working",
      highestQualification: "B.Ed - Bachelor of Education",
      education: "Arts / Design",
      collegeName: "University of Kota",
      annualIncome: "Doesn't wish to specify her income",
      companyName: "null",
      fatherOccupation: "Businessman",
      fatherJobStatus: "Retired",
      motherOccupation: "Housemaker",
      motherJobStatus: "",
      familyClass: "Middle class",
      familyValue: "Traditional Values",
      noOfBrother: "0",
      noOfBrotherMarried: "Married",
      noOfSister: "1",
      noOfSisterMarried: "Unmarried",
      manglik: false,
      createdBy: "Other",
    ),

    ShaadiItem(
      id: "AP1234567",
      name: 'Nandini Singhal',
      details:
      'It is a pleasure sharing a few words about my relative.\nShe has completed her B.Ed. Her optimistic personality is adored by one and all. She is looking for a boy with whom she can lead a happy.',
      dob: '12-Jun-1991',
      time: "11:30 AM",
      profileImg: ['https://imagesvibe.com/wp-content/uploads/2023/03/Beautiful-Indian-Girl-Images16.jpg'],
      isNew: true,
      mobile: '88441424151',
      countryCode: "+91",
      email: 'monika@gmail.com',
      fathersName: "Satish Agarwal",
      motherName: '',
      gender: 'Female',
      income: "7-10 LPA",
      accountType: "Normal",
      height: "5'2",
      ageAgo: '25 yrs',
      country: 'India',
      state: "Himachal Pradesh",
      city: "Shimla",
      category: "Agarwal",
      subCategory: "Baniya",
      maritalStatus: "Never Married",
      religion: "Hindu",
      motherTongue: "Hindi",
      community: "Agarwal",
      dietPreferences: "vegetarian",
      profession: "Currently not working",
      highestQualification: "B.Ed - Bachelor of Education",
      education: "Arts / Design",
      collegeName: "University of Kota",
      annualIncome: "Doesn't wish to specify her income",
      companyName: "null",
      fatherOccupation: "Businessman",
      fatherJobStatus: "Retired",
      motherOccupation: "Housemaker",
      motherJobStatus: "",
      familyClass: "Middle class",
      familyValue: "Traditional Values",
      noOfBrother: "0",
      noOfBrotherMarried: "Married",
      noOfSister: "1",
      noOfSisterMarried: "Unmarried",
      manglik: false,
      createdBy: "Other",
    ),

    ShaadiItem(
      id: "AP1234567",
      name: 'Nandini Singhal',
      details:
      'It is a pleasure sharing a few words about my relative.\nShe has completed her B.Ed. Her optimistic personality is adored by one and all. She is looking for a boy with whom she can lead a happy.',
      dob: '12-Jun-1991',
      time: "11:30 AM",
      profileImg: ['https://t3.ftcdn.net/jpg/05/05/18/12/360_F_505181244_DRaXgcbNrIYdNqq4I2b0jLYOeSQYq3wh.jpg'],
      isNew: true,
      mobile: '88441424151',
      countryCode: "+91",
      email: 'monika@gmail.com',
      fathersName: "Satish Agarwal",
      motherName: '',
      gender: 'Female',
      income: "7-10 LPA",
      accountType: "Normal",
      height: "5'2",
      ageAgo: '25 yrs',
      country: 'India',
      state: "Himachal Pradesh",
      city: "Shimla",
      category: "Agarwal",
      subCategory: "Baniya",
      maritalStatus: "Never Married",
      religion: "Hindu",
      motherTongue: "Hindi",
      community: "Agarwal",
      dietPreferences: "vegetarian",
      profession: "Currently not working",
      highestQualification: "B.Ed - Bachelor of Education",
      education: "Arts / Design",
      collegeName: "University of Kota",
      annualIncome: "Doesn't wish to specify her income",
      companyName: "null",
      fatherOccupation: "Businessman",
      fatherJobStatus: "Retired",
      motherOccupation: "Housemaker",
      motherJobStatus: "",
      familyClass: "Middle class",
      familyValue: "Traditional Values",
      noOfBrother: "0",
      noOfBrotherMarried: "Married",
      noOfSister: "1",
      noOfSisterMarried: "Unmarried",
      manglik: false,
      createdBy: "Other",
    ),
  ];
}

class ShaadiItem {
  final String id;
  final String name;
  final String details;
  final String dob;
  final String time;
  final List<String> profileImg;
  final bool isNew;
  final String mobile;
  final String countryCode;
  final String email;
  final String fathersName;
  final String motherName;
  final String gender;
  final String income;
  final String accountType;
  final String height;
  final String ageAgo;
  final String state;
  final String country;
  final String city;
  final String category;
  final String subCategory;
  final String maritalStatus;
  final String religion;
  final String motherTongue;
  final String community;
  final String dietPreferences;

  final String profession;
  final String highestQualification;
  final String education;
  final String collegeName;
  final String annualIncome;
  final String companyName;

  final String fatherOccupation;
  final String fatherJobStatus;
  final String familyClass;
  final String familyValue;
  final String noOfBrother;
  final String noOfBrotherMarried;
  final String noOfSister;
  final String noOfSisterMarried;

  final String motherOccupation;
  final String motherJobStatus;
  final bool manglik;
  final String createdBy;

  ShaadiItem({
    required this.id,
    required this.name,
    required this.details,
    required this.dob,
    required this.time,
    required this.profileImg,
    required this.isNew,
    required this.mobile,
    required this.countryCode,
    required this.email,
    required this.fathersName,
    required this.motherName,
    required this.gender,
    required this.income,
    required this.accountType,
    required this.height,
    required this.ageAgo,
    required this.country,
    required this.state,
    required this.city,
    required this.category,
    required this.subCategory,
    required this.maritalStatus,
    required this.religion,
    required this.motherTongue,
    required this.community,
    required this.dietPreferences,
    required this.profession,
    required this.highestQualification,
    required this.education,
    required this.collegeName,
    required this.annualIncome,
    required this.companyName,
    required this.fatherOccupation,
    required this.fatherJobStatus,
    required this.familyClass,
    required this.familyValue,
    required this.noOfBrother,
    required this.noOfBrotherMarried,
    required this.noOfSister,
    required this.noOfSisterMarried,

    required this.motherOccupation,
    required this.motherJobStatus,
    required this.manglik,
    required this.createdBy,
  });
}
